[project]
name = "dsml"
version = "0.1.0"
description = "Data Science & Machine Learning Sandbox"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "pillow>=12.3.0",
]

[tool.uv.workspace]
members = [
    "libs/nxmath",
    "libs/plotter",
    "libs/nxcli",
    "apps/plot",
    "apps/nxpillow",
    "apps/sandbox",
    "apps/shisho",
]
